export { DashboardPage as Dashboard } from "./DashboardPage";
export { InventoryPage as Inventory } from "./InventoryPage";
export { SalesInvoicesPage as Billing } from "./SalesInvoicesPage";
export { SettlementsPage as Receivables } from "./SettlementsPage";
export { ReportsPage as Reports } from "./ReportsPage";
export { SettingsPage as Settings } from "./SettingsPage";
export { RelationshipsPage as Clients } from "./RelationshipsPage";

export { DashboardPage } from "./DashboardPage";
export { SalesQuotesPage } from "./SalesQuotesPage";
export { SalesOrdersPage } from "./SalesOrdersPage";
export { SalesInvoicesPage } from "./SalesInvoicesPage";
export { SalesCreditNotesPage } from "./SalesCreditNotesPage";
export { PurchaseOrdersPage } from "./PurchaseOrdersPage";
export { GoodsReceiptsPage } from "./GoodsReceiptsPage";
export { PurchaseBillsPage } from "./PurchaseBillsPage";
export { PurchaseDebitNotesPage } from "./PurchaseDebitNotesPage";
export { InventoryPage } from "./InventoryPage";
export { SettlementsPage } from "./SettlementsPage";
export { RelationshipsPage } from "./RelationshipsPage";
export { ReportsPage } from "./ReportsPage";
export { SettingsPage } from "./SettingsPage";
